import numpy as np
x=np.array([10,20,30,40,50])
x_sum=np.sum(x)
print(x_sum)
x_mean=np.mean(x)
print(x_mean)
x_std=np.std(x)
print(x_std)
x_max=np.max(x)
print(x_max)
x_min=np.min(x)
print(x_min)
x_median=np.median(x)
print(x_median)